<img src="https://gitlab.com/bivl2ab/academico/cursos-uis/ai/ai-uis-student/raw/master/imgs/notas1_1.png" alt="Drawing" style="width:700px;">

# <center> 01. Python and Numpy Introduction! </center>


1. **Python** is a high-level, dynamically typed multiparadigm and general-purpose programming language. The main use in this course is for scientific computing, allowing a powerful environment and the use of some popular libraries are numpy, scipy and matplotlib
2. **Jupyter notebook** is a web based application to create and share dynamic documents with code, equations, text and visualization.
3. **Numpy** is a scientific library that provides a high-performance multidimensional array object, and tools for working with these arrays

##  **Outline**
1. **Python**
2. **Function and structures**
3. **Numpy**




In [ ]:
#@title **1. MONTAR EL DRIVE**  (If you are in in colab){ display-mode: "form" }
import os
from google.colab import drive
drive.mount('/content/drive')
os.chdir('/content/drive/My Drive/ML')
print(os.getcwd())

Mounted at /content/drive
/content/drive/My Drive/ML


#**1. Python**


![fig_python](https://static.javatpoint.com/interview/images/advantages-of-python.png)

Image Source: www.javatpoint.com

### **1.1 Basic types and operations: an automatic assignation**

 Python has a number of basic types including integers (int), floats (float), booleans (bool), and strings (str) and even complex number representations (complex). In python the variable declaration is **not** explicit, the interpreter try to infer the type according to the use.


In [3]:
#@title **code**  variables
a = 10.5
b = 3
c = 3.
d = "hola"
print( type(a), type(b), type(c), type(d))


print("a =",a,"; b =",b, "; c =",c)
print( "a/b =", a/b)
print( "a/c =",a/c)
print( type(a/b))
print(type(c)) # Prints "<class 'int'>"
print(c)       # Prints "3"
print(c + 1)   # Addition; prints "4"
print(c - 1)   # Subtraction; prints "2"
print(c * 2)   # Multiplication; prints "6"
print(c ** 2)  # Exponentiation; prints "9"

print(c)
c+=1
print(c)
c-=1
print(c)

<class 'float'> <class 'int'> <class 'float'> <class 'str'>
a = 10.5 ; b = 3 ; c = 3.0
a/b = 3.5
a/c = 3.5
<class 'float'>
<class 'float'>
3.0
4.0
2.0
6.0
9.0
3.0
4.0
3.0


**Important!**

- Python does not have unary increment (x++) or decrement (x--) operators
- Python implements all of the usual operators for Boolean logic, but uses English words rather than symbols (&&, ||, etc.)

In [5]:
#@title **code**  natural Boolean operation!

v = True
f = False
print(type(v))
print(v and f)
print(v or f)
print(not v)
print(v != f)

<class 'bool'>
False
True
False
True


## **1.2 Lists**

List are **resizeable arrays** that  also can have **different element** types.


In [9]:
#@title **code** working with **Lists**
xs = [3, 1, 2]    # Create a list
print(xs, xs[0])  # Prints "[3, 1, 2] 2"
print(xs[-1])     # Negative indices count from the end of the list; prints "2"
xs[2] = 'foo'     # Lists can contain elements of different types
print(xs)         # Prints "[3, 1, 'foo']"
xs.append('bar')  # Add a new element to the end of the list
print(xs)         # Prints "[3, 1, 'foo', 'bar']"
x = xs.pop()      # Remove and return the last element of the list
print(x, xs)      # Prints "bar [3, 1, 'foo']"

l = [1, 'a', 1.0, 1-1j]
print(l)

[3, 1, 2] 3
2
[3, 1, 'foo']
[3, 1, 'foo', 'bar']
bar [3, 1, 'foo']
[1, 'a', 1.0, (1-1j)]


<img src="https://gitlab.com/bivl2ab/academico/cursos-uis/ai/ai-2-uis-student/-/raw/master/imgs/icon1.png" width="200">

- What is `range` in python?
- Create a `List` with `range` that have even numbers from 100 until 500.

```
[100, 102, 104, ..., 500]
```


In [18]:
#@title **code student tabla del 9**
import numpy as np
list(range(9,91,9))
list(np.arange(9,91,9.5))

[9.0, 18.5, 28.0, 37.5, 47.0, 56.5, 66.0, 75.5, 85.0]

In [19]:
#@title **slicing**
#@markdown Python provides a particular syntax to access sublists, known as slicing.
nums = list(range(5))     # range is a built-in function that creates a list of integers
print(type(nums))
nums = [0,1,2,3,4]
print(nums)
print(type(nums))         # Prints "[0, 1, 2, 3, 4]"
print(nums[2:4])          # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(nums[2:])           # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(nums[:2])           # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(nums[:])            # Get a slice of the whole list; prints "[0, 1, 2, 3, 4]"
print(nums[:-1])          # Slice indices can be negative; prints "[0, 1, 2, 3]"
nums[2:4] = [8, 9]        # Assign a new sublist to a slice
print(nums)

<class 'list'>
[0, 1, 2, 3, 4]
<class 'list'>
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


In [36]:
#@title **Python Loops and compact Looops**
#@markdown Python provides also special mechanism to loop over the elements of a list

animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print(animal)

for i in  range(len(animals)):
    print(i)

#  to the index of each element within the body of a loop
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx, animal))
#  list comprehension

nums = list(range(5))
squares = [x ** 2 for x in nums]
print(squares)   # Prints [0, 1, 4, 9, 16]


nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print("fast way: ", even_squares)  # Prints "[0, 4, 16]"

even_squares =[]
for ant in nums:
    if ant % 2==0:
        even_squares.append(ant**2)
print("a la antigua: ", even_squares)


cat
dog
monkey
0
1
2
#0: cat
#1: dog
#2: monkey
[0, 1, 4, 9, 16]
fast way:  [0, 4, 16]
a la antigua:  [0, 4, 16]


## **1.3 Dictionaries**

The dictionaries are **special lists** like `hashes` in Java that index according to `(key, value)` pairs

In [39]:
#@title **Code** working with **Dictionaries**

# Creating a dict
d = {"DNI": 167, "nombre": "Leopoldo", "edad": 24, "nacimiento": "Lima"}

print(d)
print(d.keys())
print(d["nombre"], d["edad"], d["nacimiento"])

# Iterating a dict
for i in d.keys():
    print("la clave", i, "tiene el valor", d[i])


{'DNI': 167, 'nombre': 'Leopoldo', 'edad': 24, 'nacimiento': 'Lima'}
dict_keys(['DNI', 'nombre', 'edad', 'nacimiento'])
Leopoldo 24 Lima
la clave DNI tiene el valor 167
la clave nombre tiene el valor Leopoldo
la clave edad tiene el valor 24
la clave nacimiento tiene el valor Lima


In [44]:
c = {"marca": "Audi", "llantas": "0056", "color": "rojo", "c.c": 3800}
print(c)
print(c.keys())
print(c["color"])

{'marca': 'Audi', 'llantas': '0056', 'color': 'rojo', 'c.c': 3800}
dict_keys(['marca', 'llantas', 'color', 'c.c'])
rojo


## **1.4 Functions**

The functions are totally flexible:
-  The type of function arguments is not declared.
- structured through **indentation**, i.e. code blocks are defined by their indentation
- The implementation should be prepared to works with the data types required !
- If we initiallize  arguments, the functions work as **overload methods**
- They can return several values

In [58]:
#@title **Code** working with **Functions**

# Functions and overload methods
def f_power(x, p=2):
    return x**p


print(f_power(x=3))
print(f_power(p=4, x=3))


# Return several values
def f_power(x, p=2):
    return x**p, x*p

r = f_power(p=4, x=3)
print(r[0])

r1, r2 = f_power(p=4, x=3)
print(r1)
print(r2)

# More examples
def f_powers(x, p1=2, p2=3):
    return x**p1, x**p2

print(f_power(4))
print(f_power(4,3))
print(f_powers(4, p1=3))
xp1, xp2 = f_powers(4, p2=4, p1=3)
print("power1",xp1, "power2", xp2)



9
81
81
81
12
(16, 8)
(64, 12)
(64, 64)
power1 64 power2 256


## **1.5 More and more compact expressions**

From python we can write code in natural way, and strongly compact the expressions. See some examples.


In [59]:
#@title **Code** more **compact** expressions

# 1. The code:
a=15
if a > 10:
    s = "mayor que 10"
else:
    s = "menor que 10"
print(s)
# can be replaced by:

a = 15
s = "mayor que 10" if a > 10 else "menor que 10"
print(s)

# 2. The code:

a = [10, -4, 20, 5]

o = ["10A", "-4B", "20A", "5A"]

o = []
for i in a:
    if i<0:
        o.append(str(i)+"B")
    else:
        o.append(str(i)+"A")

print(o)

# Can be replaced by:

def convert(x):
    return str(x)+"B" if x<0 else str(x)+"A"

o = [convert(i) for i in a]
print (o)

#3. The code:

r = []
for i in range(10):
    r.append("el numero "+str(i))
print(r)

# Can be replaced by:
r = ["el numero "+str(i) for i in range(10)]
print(r)




mayor que 10
mayor que 10
['10A', '-4B', '20A', '5A']
['10A', '-4B', '20A', '5A']
['el numero 0', 'el numero 1', 'el numero 2', 'el numero 3', 'el numero 4', 'el numero 5', 'el numero 6', 'el numero 7', 'el numero 8', 'el numero 9']
['el numero 0', 'el numero 1', 'el numero 2', 'el numero 3', 'el numero 4', 'el numero 5', 'el numero 6', 'el numero 7', 'el numero 8', 'el numero 9']


# **2. Numpy**

<img src="https://gitlab.com/bivl2ab/academico/cursos-uis/ai/ai-uis-student/raw/master/imgs/numpy.png" width="400">

The `Numpy`  library allows the efficient manage of the matrices and also the matrices are expressed naturally. "NumPy was an important part of the software stack used in the discovery of gravitational waves1 and in the first imaging of a black hole2 [7]"

## **2.1 Vector and matrices from `ndarray`**

`ndarray` are homogenous (same type)  **data containers**  and **functions** to operate over the data. Operations are highly efficient.
    - It is indexed as non-negative integers
    - The number of dimensions is the `rank`
    - `shape` is a tuple with size along each dimension
Some initial notation and how the dimensions works are expressed as follows.

In [67]:
#@title **code** working with **Numpy**
import numpy as np # the convention to import numpy

a = np.array([[5,4,3,2,1,3],
              [9,8,7,6,5,6],
              [4,3,0,3,4,7],
              [5,1,1,4,1,8]])
print( "a shape", a.shape) # (filas, columnas)
print( "a rows", a.shape[0])
print( "a cols", a.shape[1])

v = np.array([2,3,4,5,6,7,3,12])
print( "v shape", v.shape)
print( "v elems", v.shape[0])
print(type(v))

x = np.array([1, 2], dtype=np.float64)   # Force a particular datatype
print(x.dtype)
print(x)

a shape (4, 6)
a rows 4
a cols 6
v shape (8,)
v elems 8
<class 'numpy.ndarray'>
float64
[1. 2.]


In [77]:
#@title **code** slicing on `ndarray` structures.
print(a)
print("una fila        " ,a[2])
print( "una fila        ",a[2,:])
print( "una columna     ",a[:,2])
print( "un elemento     ",a[-1,-1])
print( "varias filas    \n",a[0:2])
print( "varias columnas \n",a[:,1:3])
print( "una porcion     \n",a[0:2,1:3])

[[  5   4   3   2   1   3]
 [  9   8   7   6   5   6]
 [  4   3 100   3   4   7]
 [  5   1   1   4   1   8]]
una fila         [  4   3 100   3   4   7]
una fila         [  4   3 100   3   4   7]
una columna      [  3   7 100   1]
un elemento      8
varias filas    
 [[5 4 3 2 1 3]
 [9 8 7 6 5 6]]
varias columnas 
 [[  4   3]
 [  8   7]
 [  3 100]
 [  1   1]]
una porcion     
 [[4 3]
 [8 7]]


In [82]:
#@title **code:** Easy construction of matrices and vectors
b = np.zeros((2,2))   # Create an array of all zeros
print(b)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

c = np.ones((2,3))    # Create an array of all ones
print(c)              # Prints "[[ 1.  1.]]"

d = np.full((2,2), 100)  # Create a constant array
print(d)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

f = np.eye(5)         # Create a 2x2 identity matrix
print(f)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

print( "matrix identidad\n", np.eye(3))
print( "matrix identidad\n", np.identity(3))
print( "vector de ceros", np.zeros(4))
print( "matriz de ceros\n", np.zeros((3,2)))
print( "matriz de unos\n", np.ones((2,3)))
print( "vector rango", np.arange(10))
print( "vector rango", np.arange(5,10))
print( "matriz aleatoria según distribución uniforme [0,1]\n", np.random.random(size=(3,5)))
print( "vector aleatorio de enteros entre 0 y 5", np.random.randint(5, size=10))

[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[100 100]
 [100 100]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
matrix identidad
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
matrix identidad
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
vector de ceros [0. 0. 0. 0.]
matriz de ceros
 [[0. 0.]
 [0. 0.]
 [0. 0.]]
matriz de unos
 [[1. 1. 1.]
 [1. 1. 1.]]
vector rango [0 1 2 3 4 5 6 7 8 9]
vector rango [5 6 7 8 9]
matriz aleatoria según distribución uniforme [0,1]
 [[0.41388252 0.1134459  0.36690725 0.44160887 0.46742694]
 [0.22886595 0.37725722 0.06909065 0.89085774 0.98949162]
 [0.5220167  0.74288829 0.51359848 0.94301231 0.80088871]]
vector aleatorio de enteros entre 0 y 5 [4 0 3 4 0 3 2 1 0 3]


<img src="https://gitlab.com/bivl2ab/academico/cursos-uis/ai/ai-2-uis-student/-/raw/master/imgs/icon1.png" width="200">

- How works `np.linspace(A,B,C))`?. Replace A, B, and C by any number and evaluate the funtion.

- Create a random matrix of integers `Aa` with Row>4 rows and Col>10 colums.

- Which means the next notation `Aa[:2, 1:3]` ?.

- Which is the output?

In [ ]:
#@title **code student**
A =  -5#@param {type:"integer"}
B =  10#@param {type:"integer"}
C =   5#@param {type:"integer"}
Row =   5#@param {type:"integer"}
Col =   11#@param {type:"integer"}


## **2.2 `axis`**

Many functions in `numpy` can be executed from independent columns and rows  by using the argument value of `axis`.

Axes are defined for arrays with more than one dimension. A 2-dimensional array has two corresponding axes:
- the first running vertically downwards across rows (axis 0)
- the second running horizontally across columns (axis 1)

In [ ]:
#@title **code** working wit **`axis`**
z = np.random.randint(100, size=(3,4)) # Create an array filled with random values
print(z)
print(np.sum(z, axis=1))

print("suma total", np.sum(a))
print("suma eje 0", np.sum(a, axis=0))
print("suma eje 1", np.sum(a, axis=1))
print("promedio total", np.mean(a))
print("promedio eje 0", np.mean(a, axis=0))
print("promedio eje 1", np.mean(a, axis=1))

## **2.3 Math and vectorized operations with   `numpy`**


In [ ]:
#@title **code** elementwise array operations
v = np.array([10,12,13,15,20])
print(v)
print(v+1)
print(v*2)

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

#overload and as functions
print(x + y)
print(np.add(x, y))

- `*` is elementwise multiplication
- `dot` function to compute inner products of vectors   

In [ ]:
#@title **code** vector and elementwise operations
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[6,5,4],[3,2,1]])
c = np.array([[1,2],[4,5]])
print(a)
print(b)
print("--")

print(" que esta haciendo: ??")
print(a.T.dot(a))

print("matrix multiplication")
print(a.T.dot(a))
print(np.dot(a.T, a))
print("pointwise")
print(a*b)

print("--")

print("a+b\n",a+b)
print("a**2\n", a**2)
print("a*b\n",a*b)
print("a x b'\n",a.dot(b.T))
print("a' x b\n",a.T.dot(b))


## **2.4 Vectorization**

Vectorization is used to speed up the Python code without using **loop** structures. For instance, the dot product (inner product) between two vector:
$$a_{1 \times n} \cdot b_{n\times 1} = c$$


In [ ]:
#@title **code** vectorization performance
import time
a = np.random.randint(10, size=10000)
b = np.random.randint(10, size=10000)

#@markdown  Classical way
tic = time.process_time()
dot = 0.0;

for i in range(len(a)):
      dot += a[i] * b[i]

toc = time.process_time()
print("dot_product = "+ str(dot));
print("Computation time = " + str(1000*(toc - tic )) + "ms")

#@markdown  vectorized way

n_tic = time.process_time()
n_dot_product = np.dot(a, b)
n_toc = time.process_time()

print("\nn_dot_product = "+str(n_dot_product))
print("Computation time = "+str(1000*(n_toc - n_tic ))+"ms")

Another way, but with outer product (tensor product):
$$a_{n\times1}b^{T}_{1\times n} = c_{n\times n}$$

In [ ]:
#@title **code**
#@markdown classical way
tic = time.process_time()
outer_product = np.zeros((10000, 10000))

for i in range(len(a)):
    for j in range(len(b)):
        outer_product[i][j]= a[i]*b[j]

toc = time.process_time()
print("outer_product = "+ str(outer_product));
print("Computation time = "+str(1000*(toc - tic ))+"ms")
#@markdown vectorized way
n_tic = time.process_time()
outer_product = np.outer(a, b)
n_toc = time.process_time()

print("outer_product = "+str(outer_product));
print("\nComputation time = "+str(1000*(n_toc - n_tic ))+"ms")

Also, this mathematical expression:
$y^i = \sum_{j=0}^{n}\theta_{j}^{i}x_{j}^{i}=\Theta X^\top; i=\{1,2\}$, where lowercase letters correspond to elements and uppercase letters to matrices or vectors.

In [ ]:
#@title **code**
#@markdown elementwise operations
theta = np.array([0.4,0.04,0.3,0.2,0.5])
X = np.array([[1,5,8,9,7],
              [1,3,4,5,6]])
y = np.array([0.0,0.0])

for m in list(range(2)):
    result = 0
    for n in list(range(5)):
        result = result + (theta[n]*X[m,n])
    y[m] = result

print(y)
#@markdown Dot product
y = np.dot(theta,X.T)
print(y)

<img src="https://gitlab.com/bivl2ab/academico/cursos-uis/ai/ai-2-uis-student/-/raw/master/imgs/icon1.png" width="200">

What about time for this operations?

In [ ]:
#@title **code student**


### **Logical slicing**
The numpy functions also works with _boolean_ expressions. For instance to select some specific objects.

In [ ]:
#@title  **code**
a = np.array([1,8,4,10,-4,5])
print(a)
print(a>4)
i = np.array([False, True, False, True, False, True])
print(i)
print(a[a>4])

a = np.array([1,8,4,10,-4,5])
print("posiciones en a >4:", a>4)
print("elementos de a >4:",a[a>4])


## **About markdown please see the notebook complement 01**



## **Referencias**

[1] [official numpy tutorial](https://docs.scipy.org/doc/numpy/user/quickstart.html)

[2] [Datacamp tutorial of numpy](https://www.datacamp.com/community/tutorials/python-numpy-tutorial)

[3] [Other tutorial](https://www.twilio.com/blog/2017/10/basic-statistics-python-numpy-jupyter-notebook.html)

[4] [About dictionaries](https://docs.python.org/3.5/library/stdtypes.html#dict)

[5] [Mathematical functions in numpy](https://docs.scipy.org/doc/numpy/reference/routines.math.html)

[6] [More deeply in numpy](https://docs.scipy.org/doc/numpy/reference/)

[7] [Array programming with NumPy. Nature](https://www.nature.com/articles/s41586-020-2649-2)